ARG NODE_VERSION=25.8.0-alpine

FROM node:${NODE_VERSION} AS dev

WORKDIR /app

COPY package.json package-lock.json* ./

COPY frontend/package.json ./frontend/

RUN --mount=type=cache,target=/root/.npm npm ci

COPY frontend/ ./frontend/

WORKDIR /app/frontend

EXPOSE 5173

CMD ["npm", "run", "dev"]
